"""Make tenant_id non-nullable for api_keys and webhooks

Revision ID: 8425bbb0eff3
Revises: 582d5b545e98
Create Date: 2025-07-08 01:57:49.803329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8425bbb0eff3'
down_revision = '582d5b545e98'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, update existing NULL tenant_id fields to a default value (e.g., 1)
    # This assumes a default tenant with ID=1 exists.
    op.execute("UPDATE api_keys SET tenant_id = 1 WHERE tenant_id IS NULL")
    op.execute("UPDATE webhooks SET tenant_id = 1 WHERE tenant_id IS NULL")

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('webhooks', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.alter_column('tenant_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ### 