"""Add NÍVEL 5 - API Keys, Tenants, Webhooks and Multi-tenancy

Revision ID: ffb7aebb7d3c
Revises: c0c94ef5cbc5
Create Date: 2025-07-07 21:47:30.209978

"""

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision = "ffb7aebb7d3c"
down_revision = "c0c94ef5cbc5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tenants_id"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_webhook_deliveries_id"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_webhooks_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_index(op.f("ix_api_key_usage_id"), table_name="api_key_usage")
    op.drop_table("api_key_usage")
    op.drop_index(op.f("ix_tenant_settings_id"), table_name="tenant_settings")
    op.drop_index(op.f("ix_tenant_settings_tenant_id"), table_name="tenant_settings")
    op.drop_table("tenant_settings")
    op.drop_index(op.f("ix_api_keys_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_prefix"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_name"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_webhook_logs_id"), table_name="webhook_logs")
    op.drop_table("webhook_logs")
    op.drop_index(op.f("ix_permissions_id"), table_name="permissions")
    op.drop_index(op.f("ix_permissions_name"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("username", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("full_name", sa.VARCHAR(), nullable=True),
        sa.Column("hashed_password", sa.VARCHAR(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("is_superuser", sa.BOOLEAN(), nullable=True),
        sa.Column("provider", sa.VARCHAR(), nullable=True),
        sa.Column("provider_id", sa.VARCHAR(), nullable=True),
        sa.Column("oauth_access_token", sa.VARCHAR(), nullable=True),
        sa.Column("oauth_refresh_token", sa.VARCHAR(), nullable=True),
        sa.Column("totp_secret", sa.VARCHAR(), nullable=True),
        sa.Column("is_2fa_enabled", sa.BOOLEAN(), nullable=True),
        sa.Column("backup_codes", sa.VARCHAR(), nullable=True),
        sa.Column("last_totp_used", sa.VARCHAR(), nullable=True),
        sa.Column("avatar_url", sa.VARCHAR(), nullable=True),
        sa.Column("phone_number", sa.VARCHAR(), nullable=True),
        sa.Column("timezone", sa.VARCHAR(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=1)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=1)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.INTEGER(), nullable=False),
        sa.Column("permission_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("resource", sa.VARCHAR(), nullable=False),
        sa.Column("action", sa.VARCHAR(), nullable=False),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"], unique=1)
    op.create_index(op.f("ix_permissions_id"), "permissions", ["id"], unique=False)
    op.create_table(
        "webhook_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("webhook_id", sa.INTEGER(), nullable=True),
        sa.Column("level", sa.VARCHAR(length=10), nullable=False),
        sa.Column("message", sa.TEXT(), nullable=False),
        sa.Column("details", sqlite.JSON(), nullable=True),
        sa.Column("event_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("delivery_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["webhook_deliveries.id"],
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhook_logs_id"), "webhook_logs", ["id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("role_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("key_hash", sa.VARCHAR(length=128), nullable=False),
        sa.Column("key_prefix", sa.VARCHAR(length=10), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("tenant_id", sa.INTEGER(), nullable=True),
        sa.Column("scopes", sa.TEXT(), nullable=False),
        sa.Column("permissions", sa.TEXT(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("last_used_at", sa.DATETIME(), nullable=True),
        sa.Column("rate_limit_per_minute", sa.INTEGER(), nullable=True),
        sa.Column("usage_count", sa.INTEGER(), nullable=True),
        sa.Column("expires_at", sa.DATETIME(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_name"), "api_keys", ["name"], unique=False)
    op.create_index(
        op.f("ix_api_keys_key_prefix"), "api_keys", ["key_prefix"], unique=False
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=1)
    op.create_index(op.f("ix_api_keys_id"), "api_keys", ["id"], unique=False)
    op.create_table(
        "tenant_settings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("tenant_id", sa.INTEGER(), nullable=False),
        sa.Column("logo_url", sa.VARCHAR(length=500), nullable=True),
        sa.Column("primary_color", sa.VARCHAR(length=7), nullable=True),
        sa.Column("secondary_color", sa.VARCHAR(length=7), nullable=True),
        sa.Column("allow_registration", sa.BOOLEAN(), nullable=True),
        sa.Column("require_email_verification", sa.BOOLEAN(), nullable=True),
        sa.Column("enforce_2fa", sa.BOOLEAN(), nullable=True),
        sa.Column("password_policy", sqlite.JSON(), nullable=True),
        sa.Column("sso_enabled", sa.BOOLEAN(), nullable=True),
        sa.Column("sso_provider", sa.VARCHAR(length=50), nullable=True),
        sa.Column("sso_config", sqlite.JSON(), nullable=True),
        sa.Column("webhook_secret", sa.VARCHAR(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_tenant_settings_tenant_id"), "tenant_settings", ["tenant_id"], unique=1
    )
    op.create_index(
        op.f("ix_tenant_settings_id"), "tenant_settings", ["id"], unique=False
    )
    op.create_table(
        "api_key_usage",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("api_key_id", sa.INTEGER(), nullable=False),
        sa.Column("endpoint", sa.VARCHAR(length=200), nullable=False),
        sa.Column("method", sa.VARCHAR(length=10), nullable=False),
        sa.Column("status_code", sa.INTEGER(), nullable=False),
        sa.Column("response_time_ms", sa.INTEGER(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=500), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_key_id"],
            ["api_keys.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_key_usage_id"), "api_key_usage", ["id"], unique=False)
    op.create_table(
        "webhooks",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("url", sa.VARCHAR(length=500), nullable=False),
        sa.Column("secret", sa.VARCHAR(length=128), nullable=True),
        sa.Column("events", sqlite.JSON(), nullable=False),
        sa.Column("headers", sqlite.JSON(), nullable=True),
        sa.Column("timeout_seconds", sa.INTEGER(), nullable=True),
        sa.Column("retry_enabled", sa.BOOLEAN(), nullable=True),
        sa.Column("max_retries", sa.INTEGER(), nullable=True),
        sa.Column("retry_delay_seconds", sa.INTEGER(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column("last_triggered_at", sa.DATETIME(), nullable=True),
        sa.Column("last_success_at", sa.DATETIME(), nullable=True),
        sa.Column("last_failure_at", sa.DATETIME(), nullable=True),
        sa.Column("failure_count", sa.INTEGER(), nullable=True),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("tenant_id", sa.INTEGER(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_id"), "webhooks", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("description", sa.VARCHAR(), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=1)
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("webhook_id", sa.INTEGER(), nullable=False),
        sa.Column("event_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("event_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("payload", sqlite.JSON(), nullable=False),
        sa.Column("attempt_number", sa.INTEGER(), nullable=True),
        sa.Column("status_code", sa.INTEGER(), nullable=True),
        sa.Column("response_body", sa.TEXT(), nullable=True),
        sa.Column("response_headers", sqlite.JSON(), nullable=True),
        sa.Column("duration_ms", sa.INTEGER(), nullable=True),
        sa.Column("success", sa.BOOLEAN(), nullable=True),
        sa.Column("error_message", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column("delivered_at", sa.DATETIME(), nullable=True),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_id"), "webhook_deliveries", ["id"], unique=False
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("slug", sa.VARCHAR(length=50), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("contact_email", sa.VARCHAR(length=255), nullable=True),
        sa.Column("contact_phone", sa.VARCHAR(length=20), nullable=True),
        sa.Column("plan_type", sa.VARCHAR(length=50), nullable=True),
        sa.Column("max_users", sa.INTEGER(), nullable=True),
        sa.Column("max_api_keys", sa.INTEGER(), nullable=True),
        sa.Column("max_storage_mb", sa.INTEGER(), nullable=True),
        sa.Column("features", sqlite.JSON(), nullable=True),
        sa.Column("custom_domain", sa.VARCHAR(length=255), nullable=True),
        sa.Column("is_active", sa.BOOLEAN(), nullable=False),
        sa.Column("is_verified", sa.BOOLEAN(), nullable=False),
        sa.Column("subscription_expires_at", sa.DATETIME(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=1)
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=False)
    op.create_index(op.f("ix_tenants_id"), "tenants", ["id"], unique=False)
    # ### end Alembic commands ###
